Rewrite install

diff --git a/utils/install b/utils/install
--- a/utils/install
+++ b/utils/install
@@ -1,12 +1,13 @@
 #!/usr/bin/env bash
 
-
 SUPPORT_OS=(macos ubuntu)
 HOMEBREW_URL=https://raw.githubusercontent.com/Homebrew/install/master/install
-PACKAGE_CONTROL_URL=https://packagecontrol.io/Package%20Control.sublime-package
-PACKAGE_CONTROL_FILE=Package\ Control.sublime-package
-PACKAGE_CONTROL_PATH_MACOS=~/Library/Application\ Support/Sublime\ Text\ 3/Installed\ Packages
-PACKAGE_CONTROL_PATH_UBUNTU=~/.config/sublime-text-3/Installed\ Packages
+
+PACKAGE_NAME=Package\ Control
+PACKAGE_URL=https://packagecontrol.io/Package%20Control.sublime-package
+PACKAGE_FILE=Package\ Control.sublime-package
+PACKAGE_DIR_MACOS=~/Library/Application\ Support/Sublime\ Text\ 3/Installed\ Packages
+PACKAGE_DIR_UBUNTU=~/.config/sublime-text-3/Installed\ Packages
 
 # detect os, return 0 if is_macos
 function is_macos() {
@@ -52,11 +53,6 @@ function install_subl() {
           echo " => unable to install Sublime Text!"
           exit 1
         fi
-        
-        subl
-        
-        echo " => installing Package Control..."
-        curl -fsSL ${PACKAGE_CONTROL_URL} -o ${PACKAGE_CONTROL_PATH_MACOS}/${PACKAGE_CONTROL_FILE}
       ;;
       ubuntu)
         wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
@@ -64,11 +60,6 @@ function install_subl() {
         echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
         sudo apt-get update -y
         sudo apt-get install -y sublime-text
-        
-        subl
-        
-        echo " => installing Package Control..."
-        wget -q ${PACKAGE_CONTROL_URL} -O ${PACKAGE_CONTROL_PATH_UBUNTU}/${PACKAGE_CONTROL_FILE}
       ;;
       *)
         echo "This script is limited to ${supported_os[@]}"
@@ -80,4 +71,45 @@ function install_subl() {
   fi
 }
 
-install_subl
+function install_package_control() {
+    local os_name=$(get_os)
+    case "${os_name}" in
+      macos)
+        package=${PACKAGE_DIR_MACOS}/${PACKAGE_FILE}
+        if [[ ! -f "${package}" ]]; then
+          echo " => installing ${PACKAGE_NAME}..."
+          mkdir -p ${PACKAGE_DIR_MACOS}
+          curl -fsSL ${PACKAGE_URL} -o ${package}
+          if [[ $? != 0 ]]; then
+            echo " => unable to download ${PACKAGE_NAME}!"
+            exit 1
+          fi
+          echo " => installing ${PACKAGE_NAME}...done"
+        else
+          echo "${PACKAGE_NAME} already exists..."
+        fi    
+      ;;
+      ubuntu)
+        package=${PACKAGE_DIR_UBUNTU}/${PACKAGE_FILE}
+        if [[ ! -f "${package}" ]]; then
+          echo " => installing ${PACKAGE_NAME}..."
+          mkdir -p ${PACKAGE_DIR_UBUNTU}
+          wget -q ${PACKAGE_URL} -O ${package}
+          if [[ $? != 0 ]]; then
+            echo " => unable to download ${PACKAGE_NAME}!"
+            exit 1
+          fi
+          echo " => installing ${PACKAGE_NAME}...done"
+        else
+          echo "${PACKAGE_NAME} already exists..."
+        fi  
+      ;;
+      *)
+        echo "This script is limited to ${supported_os[@]}"
+        exit 1
+      ;;
+    esac
+}
+
+install_subl && install_package_control && \
+echo "Sublime Text 3 has been succesfully deployed!"
